### ISSUE TITLE
Output cell seems not working anymore

### ISSUE THREAD

**Issue by CloseChoice** [CloseChoice/dataframetrainer#54]
steps to reproduce:
start the current main branch (docker compose up + npm run dev) visit `http://localhost:5173/new_challenge/TransformWithConditions`. 

![image](https://github.com/CloseChoice/dataframetrainer/assets/31857876/5ca3c5dd-a8a7-4b74-9961-e42934f71693)
After adding a `df` at the end of the code terminal and clicking `Run` or `Test` nothing happens in the green output terminal

**Comment by giggity-hub** [comment]
Right now the output cell would just contain the output from the user code string. Shouldn't it contain the print statements from running the transform function?

**Comment by CloseChoice** [comment]
Yes, they should. But the point of this issue is that right now I do not even get the output of the user code.
