### ISSUE TITLE
POST userid to `get_next_challenge` from Frontend

### ISSUE THREAD

**Issue by CloseChoice** [CloseChoice/dataframetrainer#59]
We recently introduced the [`get_next_challenge`](https://github.com/CloseChoice/dataframetrainer/commit/28b287ab20ce8569d1c9a33b1e63449c18e831cd) endpoint. The frontend add a button to get the next challenge and make the post request with the userid in the body.

**Comment by giggity-hub** [comment]
Where should the button be added?

**Comment by CloseChoice** [comment]
Let's start by adding the button within the `new_challenge` route. So when you already have a challenge but do like to get another one the button should be right there to get to the next challenge in one click

**Comment by giggity-hub** [comment]
Since the new_challenge route can be accessed regardless of login status the session object might be empty. What should the behaviour be in that case?
Three options would be
- Display the button as inactive with a message like "login to receive tailored challenge suggestions"
- Retreive a random challenge if no session is available
- Don't display the new challenge button

**Comment by giggity-hub** [comment]
The `get_next_challenge` response with the following error message when called with a correct user id.
To reproduce select the `next-challenge-button` branch, login with google and click "New Challenge" button on `/new_challenge/`

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 104, in get_next_challenge
    cursor.execute(
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by CloseChoice** [comment]
> 

For now the second option the best we can offer. Later I would like to create guest users, which are also stored in our database and are just handled like any other user.

**Comment by CloseChoice** [comment]
> The get_next_challenge response with the following error message when called with a correct user id.
To reproduce select the next-challenge-button branch, login with google and click "New Challenge" button on /new_challenge/

To me, this looks like the DB tried to insert something and the insert failed. After this a rollback is required and if this rollback does not happen we end up in a state like this.
