### ISSUE TITLE
Fix leftovers of dev branch

### ISSUE THREAD

**Issue by CloseChoice** [CloseChoice/dataframetrainer#79]
After the merge of the dev branch (#78 ) a couple of problems remain

Still a couple of things are not working correctly:
 - Test output is not written into the test tab
 - Logging statements are written in the stdout pane
 - No resetting of stdout pane
 - the pyodide-worker.module.ts is not used, though it is the better code
 - example generation does not work

**Comment by giggity-hub** [comment]
#83 would fix those things. Instead of using string templates the challenge_name gets passed into the methods of the dft module which in my opinion makes the code a bit neater

**Comment by CloseChoice** [comment]
is closed by #83
